---
# 1. Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend
        image: kabhinyasri1911/ecommerce-backend:v1 # <--- UPDATE THIS
        ports:
        - containerPort: 5000

---
# 2. Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
# 3. Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: kabhinyasri1911/ecommerce-frontend:v1 # <--- UPDATE THIS
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
# 4. Frontend Service (Exposes the site)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer 
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000