apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUV>
    server: https://10.38.191.40:6443
  name: workload-02
contexts:
- context:
    cluster: workload-02
    user: workload-02-admin
  name: workload-02-admin@workload-02
current-context: workload-02-admin@workload-02
kind: Config
preferences: {}
users:
- name: workload-02-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lJZlN0KzJtSjRoVWd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUT>
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdzdKRmwvVlF6QUZGb1AvQS9yWm5sSXlmMkE0YnoyT1lPa05CYVhmcllXd>