apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080        # The stable port for communication
      targetPort: 8080  # The actual port inside the Flask container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Using your confirmed External IP
        image: 10.55.56.16:5000/library/backend:latest
        ports:
        - containerPort: 8080
